@baseUrl = http://localhost:3333
@authToken = {{{{authenticate.response.body.access_token}}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"Diego Fernandes",
  "email":"diego@rocketseat.com.br",
  "password":"123456"
}

###

# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/application/json

{
  "email":"diego@rocketseat.com.br",
  "password":"123456"
}

###

# @name create_question

POST {{baseUrl}}/questions
Content-Type: application/application/json
Authorization: Bearer {{authToken}}
###

# @name Fetch_recent_question

GET  {{baseUrl}}/questions
Content-Type: application/application/json
Authorization: Bearer {{authToken}}
