version: '3.9'

services:
  postgres: 
    container_name: nest-clean-pg
    image: postgres
    ports: 
     - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDAT: /data/postgres
    volumes: 
     - ./data/pg:/data/postgres